### ISSUE TITLE
How to update forked repo

### ISSUE THREAD

**Issue by hneaz** [Chicago/vision-zero-dashboard#10]
Please include this in your documentation to update forked repo if the master repo is updated.

https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

Add the remote, call it "upstream":

`git remote add upstream https://github.com/whoever/whatever.git`

Fetch all the branches of that remote into remote-tracking branches,
such as upstream/master:

`git fetch upstream`

Make sure that you're on your master branch:

`git checkout master`

Rewrite your master branch so that any commits of yours that
aren't already in upstream/master are replayed on top of that
other branch:

`git rebase upstream/master`

**Comment by geneorama** [comment]
@hneaz Thank you!  Adding this to the resources now!

**Comment by geneorama** [comment]
added to `resources\`
