### ISSUE TITLE
High Crash Corridor shapefile

### ISSUE THREAD

**Issue by wsrizal** [Chicago/vision-zero-dashboard#18]
Vision Zero has identified 43 High Crash Corridors - 70 miles of major streets with disproportionately high rates of severe crashes (ones which result in serious injury or death):

https://visionzerochicago.org/highcrashcorridors/

A shapefile would be helpful to deliver insights.

**Comment by sas1336** [comment]
@geneorama can I upload files on github?

**Comment by geneorama** [comment]
@sas1336 yes, you have contributor access. 

Are you thinking of uploading the shape file for the high crash corridors? I'm wondering if it's available elsewhere, like the open data portal.

**Comment by sas1336** [comment]
Yes, I agree it should be on the data portal. Don't think it's up there yet.

**Comment by sas1336** [comment]
For now - added the shapefiles to git at:
resources/HighCrashCorridors_CommunityAreas_20160919.zip

**Comment by geneorama** [comment]
Thanks @sas1336 !

I moved it to a data folder with the naming convention that I’ve been trying to use. 

@levyj maybe we can talk further about getting the high crash corridors online
