### ISSUE TITLE
Presentation topics for Saturday Hackathon

### ISSUE THREAD

**Issue by geneorama** [Chicago/vision-zero-dashboard#2]
Working on a list of topics for the Saturday Hackathon, which will help people know which technologies to use. There might be some differences between Mac and PC (and Linux, but less worried about those users), although I'm not sure how significant those differences are.

Right now I'm planning on starting with these topics (20 minutes)
 - Brief intro to Vision Zero
 - Installing R and R Studio
 - Getting git
 - Cloning a project
 - Using a project in R Studio
 - Markdown
 - Shiny

Not teaching anything, just giving the basic introduction to the technologies. 

Then handing it off to CDOT (10 minutes)
 - Specific goals of dashboard
 - Audience
 - Examples from other cities

I want to keep it to a specific time limit, probably **30 minutes**, which means we'll have to practice because shorter is harder.

**Comment by sas1336** [comment]
Finally, I'm here. The plan sounds good!

**Comment by geneorama** [comment]
+leaflet

**Comment by geneorama** [comment]
+ Dev ops
